spring:
  application:
    name: quiz-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/test}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

server:
  port: ${SERVER_PORT:8080}
