spring:
  application:
    name: quiz-service
  datasource:
    url: ${QUIZ_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
      format_sql: truec
    show-sql: true
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

server:
  port: 8083
  address: 0.0.0.0

feign:
  client:
    config:
      default:
        loggerLevel: full
        connectTimeout: 3000
        readTimeout: 5000