spring:
  application:
    name: quiz-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/test}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
      format_sql: truec
    show-sql: true
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  packages-to-scan: edu.goorm.quiz_service.controller
